<a href="https://colab.research.google.com/github/SUDHAN1022/Python-for-data-science/blob/main/python_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [1]:
import numpy as np

In [3]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,8,7,6,5]


In [9]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 6, 5]])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [15]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [25]:
arr[1:,3:]

array([[5, 6],
       [6, 5]])

In [28]:
arr[1:,2:4]

array([[4, 5],
       [7, 6]])

In [31]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [34]:
arr=np.arange(0,10,2)

In [35]:
arr

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
arr=np.arange(0,10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[3:]=100

In [42]:
arr1=arr

In [43]:
arr1[3:]=500
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [44]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [45]:
arr1=arr.copy()
arr1[3:]=1000
arr1

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [46]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [48]:
val=2

arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [51]:
np.random.rand(3,3)

array([[0.11712023, 0.12699918, 0.06242386],
       [0.59646713, 0.57806093, 0.31671551],
       [0.06726852, 0.88494736, 0.84069448]])

In [53]:
np.random.randn(4,4)

array([[-0.17016964, -0.33129808,  0.39152262, -1.50646906],
       [ 1.1040062 , -0.70527128,  0.97058236,  0.37458551],
       [ 0.13685272, -1.49408731, -0.4541323 , -0.39724782],
       [-0.48299988,  0.02903923,  0.10679858, -0.17538066]])

In [55]:
np.random.randint(0,100,8)

array([25, 26, 94, 43, 93, 19, 29, 64])

In [57]:
np.random.random_sample((1,5))

array([[0.85183841, 0.58004201, 0.40196567, 0.62520135, 0.73578739]])

# **PANDAS**

In [59]:
import numpy as np
import pandas as pd

In [71]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=["row1","row2","row3","row4","row5"],columns=["column1", "column2", "column3", "column4"])

In [73]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [74]:
df.to_csv("test.csv")

In [81]:
#accessing elements
#1)loc
#2)iloc
df.loc["row1"]

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int64

In [77]:
type(df.loc["row1"])

pandas.core.series.Series

In [80]:
df.iloc[0:2,0:1]

column1
row1        0
row2        4

In [79]:
df.iloc[:,1:]

column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [83]:
#converting dataframes into arrays
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [85]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [86]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [88]:
df["column1"].unique()

array([ 0,  4,  8, 12, 16])