<a href="https://colab.research.google.com/github/SUDHAN1022/Python-for-data-science/blob/main/python_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,8,7,6,5]


In [ ]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [ ]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 6, 5]])

In [ ]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [ ]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [ ]:
arr[1:,3:]

array([[5, 6],
       [6, 5]])

In [ ]:
arr[1:,2:4]

array([[4, 5],
       [7, 6]])

In [ ]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [ ]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
arr=np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:]=100

In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [ ]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [ ]:
arr1=arr.copy()
arr1[3:]=1000
arr1

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [ ]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [ ]:
val=2

arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [ ]:
np.random.rand(3,3)

array([[0.11712023, 0.12699918, 0.06242386],
       [0.59646713, 0.57806093, 0.31671551],
       [0.06726852, 0.88494736, 0.84069448]])

In [ ]:
np.random.randn(4,4)

array([[-0.17016964, -0.33129808,  0.39152262, -1.50646906],
       [ 1.1040062 , -0.70527128,  0.97058236,  0.37458551],
       [ 0.13685272, -1.49408731, -0.4541323 , -0.39724782],
       [-0.48299988,  0.02903923,  0.10679858, -0.17538066]])

In [ ]:
np.random.randint(0,100,8)

array([25, 26, 94, 43, 93, 19, 29, 64])

In [ ]:
np.random.random_sample((1,5))

array([[0.85183841, 0.58004201, 0.40196567, 0.62520135, 0.73578739]])

# **PANDAS**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=["row1","row2","row3","row4","row5"],columns=["column1", "column2", "column3", "column4"])

In [ ]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df.to_csv("test.csv")

In [ ]:
#accessing elements
#1)loc
#2)iloc
df.loc["row1"]

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int64

In [ ]:
type(df.loc["row1"])

pandas.core.series.Series

In [ ]:
df.iloc[0:2,0:1]

column1
row1        0
row2        4

In [ ]:
df.iloc[:,1:]

column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [ ]:
#converting dataframes into arrays
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [ ]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df["column1"].unique()

array([ 0,  4,  8, 12, 16])

In [ ]:
df=pd.read_csv("mercedesBenz.csv")

In [ ]:
df.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB


In [ ]:
df.describe()

ID          X10          X11          X12          X13  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean   4211.039202     0.019007     0.000238     0.074364     0.061060   
std    2423.078926     0.136565     0.015414     0.262394     0.239468   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%    2115.000000     0.000000     0.000000     0.000000     0.000000   
50%    4202.000000     0.000000     0.000000     0.000000     0.000000   
75%    6310.000000     0.000000     0.000000     0.000000     0.000000   
max    8416.000000     1.000000     1.000000     1.000000     1.000000   

               X14          X15          X16          X17          X18  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.427893     0.000713     0.002613     0.008791     0.010216  ...   
std       0.494832     0.026691     0.051061     0.093357     0.100570  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.325968     0.049656     0.311951     0.019244     0.011879   
std       0.468791     0.217258     0.463345     0.137399     0.108356   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.008791     0.000475     0.000713     0.001663  
std       0.089524     0.093357     0.021796     0.026691     0.040752  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 369 columns]

In [ ]:
df["X0"].value_counts()

X0
ak    432
y     348
z     335
x     302
ay    299
t     293
o     246
f     213
w     198
j     171
n     167
aj    162
az    161
s     116
ap    108
al     88
h      64
d      61
e      48
v      40
ai     38
m      34
af     34
am     28
i      25
at     21
u      20
ba     19
a      18
b      13
k      12
ad     12
aq     11
aw     11
r      10
ax      8
l       6
bc      6
c       6
as      6
ao      5
au      5
g       3
p       1
ae      1
av      1
an      1
ag      1
bb      1
Name: count, dtype: int64

In [ ]:
#df[df['y'>100]]

# **CSV**

In [ ]:
import pandas as pd

In [ ]:
from io import StringIO,BytesIO

In [ ]:
#data=('col1,col2,col3\n'
      #'x,y,1\n'
      #'a,b,2\n'
      #'c,d,3\n')

In [ ]:
#type(data)

str

In [ ]:
#pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
#read specific columns

#df=pd.read_csv(StringIO(data),usecols=['col1','col3'])

In [ ]:
#df

col1  col3
0    x     1
1    a     2
2    c     3

In [ ]:
#df.to_csv("sample.csv")

In [ ]:
!ls

sample.csv  sample_data


In [ ]:
data1=('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')

In [ ]:
de=pd.read_csv(StringIO(data1),dtype=float)

In [ ]:
de

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [ ]:
de['a'][1]

5.0

In [ ]:
de=pd.read_csv(StringIO(data1),dtype={'a':int,'b':float,'c':float})

In [ ]:
type(de['b'][1])

numpy.float64

In [ ]:
de.dtypes

a      int64
b    float64
c    float64
d      int64
dtype: object

# #Index columns and training delimiters

In [ ]:
data=('index,a,b,c\n'
      '4, apple, bat,5.7\n'
      '8,orange,cow,10')

In [ ]:
pd.read_csv(StringIO(data),index_col=0)

a     b     c
index                    
4       apple   bat   5.7
8      orange   cow  10.0

In [ ]:
data=('a,b,c\n'
      '4,apple,bat\n'
      '8,orange,cow,')

In [ ]:
pd.read_csv(StringIO(data))

index       a     b     c
0      4   apple   bat   5.7
1      8  orange   cow  10.0

# #usecol and index_col

In [ ]:
data=('a,b,c\n'
      '4,apple,bat,\n'
      '8,orange,cow')

In [ ]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)

b    c
0   apple  bat
1  orange  cow

#quoting and escape

In [ ]:
data='a,b\n"hello,\\"bob\\",nice to see you",5'

In [ ]:
from os import ST_RDONLY
pd.read_csv(StringIO(data),escapechar="\\")

a  b
0  hello,"bob",nice to see you  5

#url to csv

In [ ]:
df=pd.read_csv('')

# **Leetcode 2877**

In [99]:
import pandas as pd

In [102]:
student_data=[
  [1, 15],
  [2, 11],
  [3, 11],
  [4, 20]
]

In [103]:
pd.DataFrame(data=student_data,columns=["student_id","age"])

student_id  age
0           1   15
1           2   11
2           3   11
3           4   20